{% set version = "0.3.13" %}

package:
  name: pygeobase
  version: {{ version }}

source:
  fn: pygeobase-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pygeobase/pygeobase-{{ version }}.tar.gz
  sha256: 49f2af0b9dd4e147e8abd51bb36f66e174f29db86c5ac0b14a8b379709d1f6b1

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pyscaffold >=2.4rc1,<2.5a0
    - six
    - setuptools_scm >=1.7
  run:
    - python
    - numpy
    - setuptools

test:
  imports:
    - pygeobase
    - pygeobase.io_base
    - pygeobase.object_base

about:
  home: https://github.com/TUW-GEO/pygeobase
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Base class definition for I/O interfaces of poets°'

extra:
  recipe-maintainers:
    - cpaulik
