{% set version = "0.3.18" %}

package:
  name: pygeobase
  version: {{ version }}

source:
  fn: pygeobase-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pygeobase/pygeobase-{{ version }}.tar.gz
  sha256: 52bc4f0bbf0b42143d9476d418c5217eebc6ecf7d72d9c4c698296ca0dda2f91

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pyscaffold >=2.4rc1,<2.5a0
    - six
    - setuptools_scm >=1.7
  run:
    - python
    - numpy
    - setuptools

test:
  imports:
    - pygeobase
    - pygeobase.io_base
    - pygeobase.object_base

about:
  home: https://github.com/TUW-GEO/pygeobase
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Base class definition for I/O interfaces of poets°'

extra:
  recipe-maintainers:
    - cpaulik
