{% set version = "0.6.0" %}

package:
  name: pygeobase
  version: {{ version }}

source:
  fn: pygeobase-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pygeobase/pygeobase-{{ version }}.tar.gz
  sha256: 10ba4ba532a9c76af82b5407543db6a529aa5663b963a0ddb9fc963b586081c5

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - pyscaffold >=2.4rc1,<2.5a0
    - six
    - setuptools_scm >=1.7
  run:
    - python
    - numpy
    - setuptools

test:
  imports:
    - pygeobase
    - pygeobase.io_base
    - pygeobase.object_base

about:
  home: https://github.com/TUW-GEO/pygeobase
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Base class definition for I/O interfaces of poets°

extra:
  recipe-maintainers:
    - cpaulik
