travis:
  secure:
    BINSTAR_TOKEN: goIS223u4grxCZf44FcTmmIxHIOOmyTFENHin3zgK9nNMlMB1LUiNvYZNNpaAgwEblllj2ImUVOUjULaVc57gJu9/C9PjxCCwhTop6Npy6qD3rSB1WCV7WVQqkGFvS9usmQoIYakfCuY0hdc48WIZAUgpkMfKBoDR08/AxB4wDn01eOmqwhmQVM+7eU/EM2qiSPEAtYkuwSg6QPIOwPR91OTEwQmxdwvnksqn66Pkj3e9b3DXFCtteAgu1EkkN9GH2fXEILd9l45oumIfb6heNMZDJfE3oEwmOXXi3M8/ip4wzRTRNimjSk0bSg/7FjfiXkBG5zrXywKXWjyVEJUrPdRTxlgt3nkETONywTP3fox67HWDnbU7biJJJq4DqukLPM8N7zg1sjNP1QhoWou2P1faJXmBEYDkLz46nVJdD0iGDFpEow/wi6QPIt71xOy6ddnCcKIkdeYPDhP3yf3IAYoQT6E8tqld5ISrbY7lUFgdvRuQcMmvmcMjKL76j62FiC/GADNhCdw+kSOfOdP0F0paoOxvJD7pEn8CDU8O0MOgjtGPFZ3uYqo924/Cpn5j8DJBl/kRViu5WJfWDSQJ70fVi38juQlM9yn3FZh241QYDlVXLQNu18+isyOoKmqY3lO5L0TZsV1E6AEGz3Iq8ZYgIHrf74pi3vLnj/ex6w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
