travis:
  secure:
    BINSTAR_TOKEN: b2xFccB6oeW1I+9Hhpro8tKgGhz0shCLomtWa0SUQEObXzYbRH27RS1MWk6yWCyK9U1C4RdM+Gli6eisAwvkAzL+cU/Q4OIXF5vyV4c7kxS0iAdTeJMJr3TQ2B2+A1cbhGMt54YXMYHs2oyfx/vazRoDB9HuTOsVgvd5deA2Y4oR6dizZEr0cHH/gU5mlM0U+wnm8YIHeWZDOjcCMuvF3iFYoYimZaqnouMOT/3xHdhInG9kaHEK7DKucSzy2oaa0rrSDN1XN5DKxiS9uiIYbkJfeER0HXlFfXaFfZgapO2Zal8sV/aTDcKOqnZKb/vmZrBIseoTQ2/H77wW8cl/eXkxLvJZJwl1ltWVu8PYsp1wT7OA7v/SiM3DMlpw0oIig4FYPxUNl6INfvN8tRkWVsFVTX8h/XyE+sUPudXHw+TjUDAo0uwabs54YpPMLtpzvuVc5x2fJZj3vEWhC4q0RfER0a8zr9J63OvlFpSsmTJVO5XlryY07ezzRlZMn+/jyQTc354DlbCNGKIdSsxWYoOY7FyhmaUmELmbhYQEatwcWlrB6Ta7scvr4JM4xnX7eiQyV7Vc9H+X9IJ5bJhKMQWKOzVVgVbUEZp5VJDLcrBZT/qWuQx2Fgl3w5iMdEiR6ynNMnvn1iWf9NIv/0vs+yEUgvjNRO4KTt7KNKP7WG8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
